[tool.poetry]
name = "template-django"
version = "0.1.1"
description = "Template for starting a new Django app"
authors = ["Rory Strahan-Mauk <rorystrahanmauk@gmail.com>"]
license = "GNU Affero General Public License v3.0"

[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = "^2.9.3"
Django = "^4.0"
django-permissions-policy = "^4.6.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
coverage = "^6.2"
honcho = "^1.1.0"
ipython = "^7.30.1"
jinja-cli = "^1.2.2"
mypy = "^0.930"
pytest = "^6.2.5"

[build-system]
requires = [
    "poetry-core>=1.0.7",
]
build-backend = "poetry.core.masonry.api"
