[tool.poetry]
name = "template-django"
version = "0.1.0"
description = "Template for starting a new Django app"
authors = ["Rory Strahan-Mauk <rorystrahanmauk@gmail.com>"]
license - "GNU Affero General Public License v3.0"

[tool.poetry.dependencies]
python = "^3.9"
psycopg2 = "^2.9.1"
Django = "^3.2.6"
django-permissions-policy = "^4.2.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
flake8 = "^3.9.2"
coverage = "^5.5"
honcho = "^1.0.1"
pytest = "^6.2.4"
ipython = "^7.26.0"

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools>=57.4.0",
    "wheel>=0.37.0",
    "cython>=0.29.24"
]
build-backend = "poetry.core.masonry.api"
